# Generated by Django 5.0.1 on 2024-01-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='segmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Image', models.ImageField(upload_to='images/%data')),
            ],
        ),
    ]
